/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as LessonsCourseIdRouteImport } from './routes/lessons.$courseId'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as CoursesLevelIdRouteImport } from './routes/courses.$levelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsCourseIdRoute = LessonsCourseIdRouteImport.update({
  id: '/lessons/$courseId',
  path: '/lessons/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesLevelIdRoute = CoursesLevelIdRouteImport.update({
  id: '/courses/$levelId',
  path: '/courses/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$levelId': typeof CoursesLevelIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/lessons/$courseId': typeof LessonsCourseIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$levelId': typeof CoursesLevelIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/lessons/$courseId': typeof LessonsCourseIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement': typeof PlacementRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/courses/$levelId': typeof CoursesLevelIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/lessons/$courseId': typeof LessonsCourseIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/levels'
    | '/login'
    | '/placement'
    | '/profile'
    | '/register'
    | '/courses/$levelId'
    | '/lesson/$id'
    | '/lessons/$courseId'
    | '/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/levels'
    | '/login'
    | '/placement'
    | '/profile'
    | '/register'
    | '/courses/$levelId'
    | '/lesson/$id'
    | '/lessons/$courseId'
    | '/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/levels'
    | '/login'
    | '/placement'
    | '/profile'
    | '/register'
    | '/courses/$levelId'
    | '/lesson/$id'
    | '/lessons/$courseId'
    | '/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsRoute: typeof LevelsRoute
  LoginRoute: typeof LoginRoute
  PlacementRoute: typeof PlacementRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  CoursesLevelIdRoute: typeof CoursesLevelIdRoute
  LessonIdRoute: typeof LessonIdRoute
  LessonsCourseIdRoute: typeof LessonsCourseIdRoute
  QuizIdRoute: typeof QuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$courseId': {
      id: '/lessons/$courseId'
      path: '/lessons/$courseId'
      fullPath: '/lessons/$courseId'
      preLoaderRoute: typeof LessonsCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$levelId': {
      id: '/courses/$levelId'
      path: '/courses/$levelId'
      fullPath: '/courses/$levelId'
      preLoaderRoute: typeof CoursesLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsRoute: LevelsRoute,
  LoginRoute: LoginRoute,
  PlacementRoute: PlacementRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  CoursesLevelIdRoute: CoursesLevelIdRoute,
  LessonIdRoute: LessonIdRoute,
  LessonsCourseIdRoute: LessonsCourseIdRoute,
  QuizIdRoute: QuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
