# Generated by Django 5.2.11 on 2026-05-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_option_quiz_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='caption_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='courses.level'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
