# Generated by Django 5.2.11 on 2026-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_duration_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/options/images/'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_video',
            field=models.FileField(blank=True, null=True, upload_to='quiz/options/videos/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/questions/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_video',
            field=models.FileField(blank=True, null=True, upload_to='quiz/questions/videos/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
