# Generated by Django 5.2.11 on 2026-06-01 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_option_option_image_option_option_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/lesson_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='videos/lesson/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/option/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/option/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/question/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/question/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
