# Generated by Django 5.2.11 on 2026-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='am_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='am_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='am_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='am_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
