/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlacementTestRouteImport } from './routes/placement-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationRouteImport } from './routes/_app/notification'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppQuizQuizIdRouteImport } from './routes/_app/quiz.$quizId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app/courses_.$courseId'
import { Route as AppCommunityPostIdRouteImport } from './routes/_app/community_.$postId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementTestRoute = PlacementTestRouteImport.update({
  id: '/placement-test',
  path: '/placement-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationRoute = AppNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizQuizIdRoute = AppQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses_/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityPostIdRoute = AppCommunityPostIdRouteImport.update({
  id: '/community_/$postId',
  path: '/community/$postId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/placement-test': typeof PlacementTestRoute
  '/register': typeof RegisterRoute
  '/community': typeof AppCommunityRoute
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/notification': typeof AppNotificationRoute
  '/profile': typeof AppProfileRoute
  '/community/$postId': typeof AppCommunityPostIdRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/placement-test': typeof PlacementTestRoute
  '/register': typeof RegisterRoute
  '/community': typeof AppCommunityRoute
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/notification': typeof AppNotificationRoute
  '/profile': typeof AppProfileRoute
  '/community/$postId': typeof AppCommunityPostIdRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/placement-test': typeof PlacementTestRoute
  '/register': typeof RegisterRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notification': typeof AppNotificationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/community_/$postId': typeof AppCommunityPostIdRoute
  '/_app/courses_/$courseId': typeof AppCoursesCourseIdRoute
  '/_app/quiz/$quizId': typeof AppQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/placement-test'
    | '/register'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/notification'
    | '/profile'
    | '/community/$postId'
    | '/courses/$courseId'
    | '/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/placement-test'
    | '/register'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/notification'
    | '/profile'
    | '/community/$postId'
    | '/courses/$courseId'
    | '/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/placement-test'
    | '/register'
    | '/_app/community'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/notification'
    | '/_app/profile'
    | '/_app/community_/$postId'
    | '/_app/courses_/$courseId'
    | '/_app/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlacementTestRoute: typeof PlacementTestRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-test': {
      id: '/placement-test'
      path: '/placement-test'
      fullPath: '/placement-test'
      preLoaderRoute: typeof PlacementTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notification': {
      id: '/_app/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof AppNotificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/$quizId': {
      id: '/_app/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AppQuizQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses_/$courseId': {
      id: '/_app/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community_/$postId': {
      id: '/_app/community_/$postId'
      path: '/community/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof AppCommunityPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationRoute: typeof AppNotificationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCommunityPostIdRoute: typeof AppCommunityPostIdRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppQuizQuizIdRoute: typeof AppQuizQuizIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationRoute: AppNotificationRoute,
  AppProfileRoute: AppProfileRoute,
  AppCommunityPostIdRoute: AppCommunityPostIdRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppQuizQuizIdRoute: AppQuizQuizIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlacementTestRoute: PlacementTestRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
