import { createContext, useContext, useCallback } from 'react'
import { useAuth } from './AuthContext.jsx'
import api from '../api/client.js'

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    levels: 'Levels',
    curriculum: 'Curriculum',
    progress: 'Progress',
    certificates: 'Certificates',
    community: 'Community',
    notifications: 'Notifications',
    profile: 'Profile',
    logout: 'Logout',

    // Dashboard
    curriculumFlow: 'Curriculum Flow',
    learner: 'Learner',
    progressTracker: 'Progress Tracker',
    welcomeBack: 'Welcome back',
    continueJourney: 'Continue your learning journey. Keep improving step by step.',
    completedLessons: 'Completed Lessons',
    successfulQuizzes: 'Successful Quizzes',
    failedQuizzes: 'Failed Quizzes',
    avgQuizScore: 'Avg Quiz Score',
    streak: 'Streak',
    recentActivities: 'Recent Activities',
    viewAll: 'View All →',
    noRecentActivity: 'No recent activity yet. Start learning!',
    recommended: 'Recommended',
    completeForRecommendations: 'Complete lessons to get recommendations.',
    quickActions: 'Quick Actions',
    continueLearning: '📖 Continue Learning',
    viewProgress: '📊 View Progress',
    retakeLevel: '🔄 Retake Level',
    day: 'day',
    days: 'days',

    // Levels
    structuredPathway: 'Structured Pathway',
    proficiencyLevels: 'Proficiency Levels',
    academicProgress: 'Academic Progress',
    unlockedLevels: 'Active Levels',
    pathwayMetrics: 'Pathway Metrics',
    chapter: 'Chapter',
    locked: 'Locked',
    active: 'Active',
    lockedContent: 'Locked Content',
    beginJourney: 'Begin Journey',
    takeLevelQuiz: 'Take Level Quiz',
    noLevelsFound: 'No levels found',

    // Courses
    availableModules: 'Available Modules',
    selectModule: 'Select a module to start learning',
    backToLevels: 'Back to Levels',
    viewLessons: 'View Lessons',
    noModules: 'No modules available',

    // Lessons
    yourLearningPath: 'Your Learning Path',
    workThroughLessons: 'Work through each lesson in order — unlock the next as you complete them.',
    backToModules: '← Back to Modules',
    open: 'Open',
    completed: 'Completed',
    noLessons: 'No lessons in this module yet',

    // Lesson Detail
    lesson: 'Lesson',
    backToModule: '← Back to module',
    markComplete: 'Mark as complete',
    saving: 'Saving…',
    takeQuiz: 'Take quiz →',
    askAiTutor: 'Ask AI Tutor',
    closeTutor: 'Close Tutor',
    askMeAnything: 'Ask me anything about this lesson!',
    thinking: 'Thinking…',
    send: 'Send',
    askQuestion: 'Ask a question…',

    // Progress
    yourLearningProgress: 'Your Learning Progress',
    trackYourJourney: 'Track your journey, monitor your habits, and record your achievements.',
    yourCurrentLevel: 'Your Current Level',
    passedQuizzes: 'Passed Quizzes',
    successRate: 'Success Rate',
    streakDays: 'Streak Days',
    quizPerformance: 'Quiz Performance',
    totalQuizAttempts: 'Total Quiz Attempts',
    quizSuccessRate: 'Quiz Success Rate',
    takeMoreQuizzes: 'Take More Quizzes',
    learningSummary: 'Learning Summary',
    lessonsCompleted: 'Lessons Completed',
    studyStreak: 'Study Streak',
    readyForNewLessons: 'Ready to start new lessons?',
    exploreNow: 'Start Now →',

    // Community
    communityHub: 'Community Hub',
    connectShareLearn: 'Connect, share, and learn together',
    newDiscussion: 'New Discussion',
    reportsAgainstMe: 'Reports Against Me',
    noPostsYet: 'No posts yet. Be the first to start a discussion!',
    comments: 'comments',
    postReply: 'Post Reply',
    writeReply: 'Write a reply...',
    createDiscussion: 'Create New Discussion',
    title: 'Title',
    content: 'Content',
    cancel: 'Cancel',
    post: 'Post Discussion',
    edit: 'Edit',
    delete: 'Delete',
    report: 'Report',

    // Notifications
    notifications_title: 'Notifications',
    stayUpdated: 'Stay updated with warnings and reports',
    warnings: 'Warnings',
    reportsAgainstYou: 'Reports Against You',
    noWarnings: 'No Warnings',
    noWarningsMsg: 'You have no warnings. Keep up the good work!',

    // Profile
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    courseProgress: 'Course Progress',
    noProgressYet: 'No course progress yet. Start learning to see your progress!',
    quizAverage: 'Quiz Average',
    currentLevel: 'Current Level',

    // Common
    loading: 'Loading...',
    retry: 'Try Again',
    save: 'Save Changes',
    forgotPassword: 'Forgot Password?',
    updatePassword: 'Update Password',
    loadingProfile: 'Loading profile...',
    failedProfile: 'Failed to load profile',
    lessonsUnit: 'lessons',
    // Level name translations
    levelName_Beginner: 'Beginner',
    levelName_Intermediate: 'Intermediate',
    levelName_Advanced: 'Advanced',
    // Curriculum
    curriculumModules: 'Curriculum / Modules',
    moduleLesson: 'Module / Lesson',
    curriculumRoadmap: 'Learning Roadmap',
    fullLearningPath: 'Your Full Learning Path',
    curriculumSubtitle: 'Every level, module, and lesson — your complete journey from start to certificate.',
    overallProgress: 'Overall Progress',
    noCurriculum: 'No curriculum available',
    checkBackSoon: 'Check back soon.',
    levelLabel: 'Level',
    moduleLabel: 'Module',
    inProgress: 'In Progress',
    completedBadge: 'Completed',
    quizBadge: 'Quiz',
    doneBadge: 'Done',
    readyBadge: 'Ready',
    certUnlocked: 'Certificate Unlocked!',
    levelCertLabel: 'Level Certificate',
    completeAllToUnlock: 'Complete all lessons to unlock',
    viewCertificate: 'View Certificate',
    journeyComplete: 'Journey Complete!',
    finishLine: 'Finish Line',
    // Quiz
    quizTitle: 'Quiz',
    answered: 'answered',
    answerAllToSubmit: 'Answer all questions to submit',
    submitQuiz: 'Submit quiz',
    submitting: 'Submitting…',
    pleaseAnswerAll: 'Please answer all',
    remainingQuestions: 'remaining question(s) before submitting.',
    questionRequiresAnswer: 'This question requires an answer.',
    reviewTitle: 'Review',
    passed: 'Passed',
    didNotPass: 'Did not pass',
    correct: 'correct',
    score: 'Score',
    passingScore: 'Passing score',
    yourAnswer: 'Your answer',
    correctAnswer: 'Correct answer',
    goToNextLesson: 'Go to Next Lesson →',
    retakeQuiz: 'Retake Quiz',
    backToModule: '← Back to module',
    levelComplete: 'Level Complete!',
    congratulations: 'Congratulations!',
    levelCertificateMsg: 'You have successfully completed the',
    levelCertificateMsg2: 'level and earned a certificate.',
    viewMyCertificate: '🏅 View My Certificate',
    backToLevels2: 'Back to Levels',

    // Certificates
    achievements: 'Achievements',
    certificatesTitle: 'Certificates',
    certSubtitle: 'Tap a certificate to view, or use the Download button to save a PDF.',
    earned: 'earned',
    loadingCertificates: 'Loading certificates…',
    noCertificates: 'No certificates earned yet. Complete a level to unlock your first certificate.',
    tapToOpen: 'Tap to open',
    issued: 'Issued',
    downloading: 'Downloading…',
    downloadPdf: 'Download PDF',

    // Notifications extra
    notificationsSubtitle: 'Stay updated with warnings and reports',
    warningsTab: 'Warnings',
    reportsTab: 'Reports Against You',
    noWarningsTitle: 'No Warnings',
    noWarningsText: 'You have no warnings. Keep up the good work!',
    noReportsTitle: 'No Reports',
    noReportsText: 'No one has reported you. Keep being a positive community member!',
    adminWarning: 'Admin Warning',
    warningDisappears: 'This warning will disappear automatically after 30 days.',
    reportFiled: 'Report Filed Against You',
    reason: 'Reason',
    communityGuidelines: 'Community Guidelines',
    communityGuidelinesText: 'Be respectful, help others, and follow our community rules to maintain a positive learning environment.',
    needHelp: 'Need Help?',
    needHelpText: 'If you have questions about a warning or report, please contact an admin.',
    justNow: 'Just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    loadingNotifications: 'Loading notifications...',
    failedNotifications: 'Failed to load notifications',

    // Levels extra
    structuredPathway: 'Structured Pathway',
    proficiencyLevels: 'Proficiency Levels',
    academicProgress: 'Academic Progress',
    unlockedLevelsDetermineCapacities: 'Unlocked levels determine active learning capacities.',
    pathwayMetrics: 'Pathway Metrics',
    activeLevels: 'Active Levels',
    curriculumFlowTitle: 'Curriculum Flow',
    chapter: 'Chapter',
    levelCompass: 'Level Compass',
    lockedContent: 'Locked Content',
    beginJourney: 'Begin Journey',
    takeLevelQuiz: 'Take Level Quiz',
    completeAllLessons: 'Complete all lessons & quizzes in the previous level first',
    passPreviousQuiz: "Pass the previous level's final quiz to unlock",

    // Progress extra
    skillPlan: 'Skill Plan',
    exams: 'Exams',
    overview: 'Overview',
    times: 'times',
    quizzes: 'quizzes',
    days_unit: 'days',
    grammarQuote: '"Knowing grammar is the path to freedom."',
    exploreChapters: 'Explore chapter courses and interactive tests now.',
    chapter03: 'Chapter 03: Personal Study Records',

    returnToDashboard: 'Return to Dashboard',
    completedLesson: 'Completed',
    passedQuizScore: 'Passed quiz · Score',
    lessonsCompletedOf: 'lessons completed',
  },

  am: {
    // Nav
    dashboard: 'ዳሽቦርድ',
    levels: 'ደረጃዎች',
    curriculum: 'ስርዓተ ትምህርት',
    progress: 'እድገት',
    certificates: 'የምስክር ወረቀቶች',
    community: 'ማህበረሰብ',
    notifications: 'ማሳወቂያዎች',
    profile: 'መገለጫ',
    logout: 'ውጣ',

    // Dashboard
    curriculumFlow: 'የትምህርት ፍሰት',
    learner: 'ተማሪ',
    progressTracker: 'የእድገት መቆጣጠሪያ',
    welcomeBack: 'እንኳን ደህና መጡ',
    continueJourney: 'የትምህርት ጉዞዎን ይቀጥሉ። እርምጃ በእርምጃ እያሻሻሉ ይሂዱ።',
    completedLessons: 'የተጠናቀቁ ትምህርቶች',
    successfulQuizzes: 'የተሳኩ ፈተናዎች',
    failedQuizzes: 'ያልተሳኩ ፈተናዎች',
    avgQuizScore: 'አማካይ የፈተና ነጥብ',
    streak: 'ተከታታይ ቀናት',
    recentActivities: 'የቅርብ ጊዜ እንቅስቃሴዎች',
    viewAll: 'ሁሉንም ይዩ →',
    noRecentActivity: 'እስካሁን ምንም እንቅስቃሴ የለም። መማር ይጀምሩ!',
    recommended: 'የሚመከር',
    completeForRecommendations: 'ምክሮችን ለማግኘት ትምህርቶችን ያጠናቅቁ።',
    quickActions: 'ፈጣን እርምጃዎች',
    continueLearning: '📖 መማርን ይቀጥሉ',
    viewProgress: '📊 እድገት ይመልከቱ',
    retakeLevel: '🔄 ደረጃ ይድገሙ',
    day: 'ቀን',
    days: 'ቀናት',

    // Levels
    structuredPathway: 'የተደራጀ መንገድ',
    proficiencyLevels: 'የብቃት ደረጃዎች',
    academicProgress: 'የትምህርት እድገት',
    unlockedLevels: 'ንቁ ደረጃዎች',
    pathwayMetrics: 'የመንገድ መለኪያዎች',
    chapter: 'ምዕራፍ',
    locked: 'ተቆልፏል',
    active: 'ንቁ',
    lockedContent: 'ተቆልፏል',
    beginJourney: 'ጉዞ ይጀምሩ',
    takeLevelQuiz: 'የደረጃ ፈተና ይውሰዱ',
    noLevelsFound: 'ምንም ደረጃ አልተገኘም',

    // Courses
    availableModules: 'ሞጁሎች',
    selectModule: 'ለመማር ሞጁል ይምረጡ',
    backToLevels: 'ወደ ደረጃዎች ተመለስ',
    viewLessons: 'ትምህርቶችን ይዩ',
    noModules: 'ምንም ሞጁሎች የሉም',

    // Lessons
    yourLearningPath: 'የትምህርት መንገድዎ',
    workThroughLessons: 'እያንዳንዱን ትምህርት በቅደም ተከተል ይስሩ — ሲጠናቀቁ ቀጣዩን ይክፈቱ።',
    backToModules: '← ወደ ሞጁሎች ተመለስ',
    open: 'ክፍት',
    completed: 'ተጠናቅቋል',
    noLessons: 'እስካሁን ምንም ትምህርቶች የሉም',

    // Lesson Detail
    lesson: 'ትምህርት',
    backToModule: '← ወደ ሞጁሉ ተመለስ',
    markComplete: 'እንደተጠናቀቀ ምልክት አድርግ',
    saving: 'በመቀመጥ ላይ…',
    takeQuiz: 'ፈተና ውሰድ →',
    askAiTutor: 'AI አስተማሪን ይጠይቁ',
    closeTutor: 'አስተማሪ ዝጋ',
    askMeAnything: 'ስለዚህ ትምህርት ማንኛውም ነገር ይጠይቁኝ!',
    thinking: 'በማሰብ ላይ…',
    send: 'ላክ',
    askQuestion: 'ጥያቄ ይጠይቁ…',

    // Progress
    yourLearningProgress: 'የትምህርት እድገትዎ',
    trackYourJourney: 'ጉዞዎን ይከታተሉ፣ ልምዶቻቸውን ይቆጣጠሩ፣ ስኬቶቻቸውን ይመዝግቡ።',
    yourCurrentLevel: 'የአሁን ደረጃዎ',
    passedQuizzes: 'ያለፉ ፈተናዎች',
    successRate: 'ስኬት ደረጃ',
    streakDays: 'ተከታታይ ቀናት',
    quizPerformance: 'የፈተና አፈፃፀም',
    totalQuizAttempts: 'ጠቅላላ የፈተና ሙከራዎች',
    quizSuccessRate: 'የፈተና ስኬት ደረጃ',
    takeMoreQuizzes: 'ተጨማሪ ፈተናዎች ውሰዱ',
    learningSummary: 'የትምህርት ማጠቃለያ',
    lessonsCompleted: 'የተጠናቀቁ ትምህርቶች',
    studyStreak: 'የጥናት ተከታታይ ቀናት',
    readyForNewLessons: 'አዲስ ትምህርቶች ለመጀመር ዝግጁ ነዎት?',
    exploreNow: 'አሁን ይጀምሩ →',

    // Community
    communityHub: 'የማህበረሰብ ማዕከል',
    connectShareLearn: 'ተገናኙ፣ ያካፍሉ፣ አብረው ይማሩ',
    newDiscussion: 'አዲስ ውይይት',
    reportsAgainstMe: 'ስለ እኔ ሪፖርቶች',
    noPostsYet: 'እስካሁን ምንም ልጥፍ የለም። የመጀመሪያው ውይይት ይጀምሩ!',
    comments: 'አስተያየቶች',
    postReply: 'ምላሽ ይስጡ',
    writeReply: 'ምላሽ ይጻፉ...',
    createDiscussion: 'አዲስ ውይይት ፍጠር',
    title: 'ርዕስ',
    content: 'ይዘት',
    cancel: 'ሰርዝ',
    post: 'ውይይት ይለጥፉ',
    edit: 'አስተካክል',
    delete: 'ሰርዝ',
    report: 'ሪፖርት',

    // Notifications
    notifications_title: 'ማሳወቂያዎች',
    stayUpdated: 'ማስጠንቀቂያዎችን እና ሪፖርቶችን ይከታተሉ',
    warnings: 'ማስጠንቀቂያዎች',
    reportsAgainstYou: 'ስለ እርስዎ ሪፖርቶች',
    noWarnings: 'ምንም ማስጠንቀቂያ የለም',
    noWarningsMsg: 'ምንም ማስጠንቀቂያ የለዎትም። እያሻሻሉ ይቀጥሉ!',

    // Profile
    editProfile: 'መገለጫ አስተካክል',
    changePassword: 'የይለፍ ቃል ቀይር',
    courseProgress: 'የኮርስ እድገት',
    noProgressYet: 'እስካሁን ምንም የኮርስ እድገት የለም። ለማየት መማር ይጀምሩ!',
    quizAverage: 'አማካይ ፈተና',
    currentLevel: 'የአሁን ደረጃ',

    // Common
    loading: 'በመጫን ላይ...',
    retry: 'እንደገና ሞክር',
    save: 'ለውጦችን አስቀምጥ',
    forgotPassword: 'የይለፍ ቃል ረሳኸው?',
    updatePassword: 'የይለፍ ቃሉን አዘምን',
    loadingProfile: 'መገለጫ በመጫን ላይ...',
    failedProfile: 'መገለጫ መጫን አልተሳካም',
    lessonsUnit: 'ትምህርቶች',
    // Level name translations
    levelName_Beginner: 'ጀማሪ',
    levelName_Intermediate: 'መካከለኛ',
    levelName_Advanced: 'ከፍተኛ',
    // Curriculum
    curriculumModules: 'ስርዓተ ትምህርት / ሞጁሎች',
    moduleLesson: 'ሞጁል / ትምህርት',
    curriculumRoadmap: 'የትምህርት ካርታ',
    fullLearningPath: 'ሙሉ የትምህርት መንገድዎ',
    curriculumSubtitle: 'እያንዳንዱ ደረጃ፣ ሞጁል እና ትምህርት — ከጅምር እስከ የምስክር ወረቀት ሙሉ ጉዞዎ።',
    overallProgress: 'አጠቃላይ እድገት',
    noCurriculum: 'ምንም ስርዓተ ትምህርት የለም',
    checkBackSoon: 'በቅርቡ ይመልሱ።',
    levelLabel: 'ደረጃ',
    moduleLabel: 'ሞጁል',
    inProgress: 'በሂደት ላይ',
    completedBadge: 'ተጠናቅቋል',
    quizBadge: 'ፈተና',
    doneBadge: 'ተጠናቅቋል',
    readyBadge: 'ዝግጁ',
    certUnlocked: 'የምስክር ወረቀት ተከፈተ!',
    levelCertLabel: 'የደረጃ የምስክር ወረቀት',
    completeAllToUnlock: 'ለመክፈት ሁሉንም ትምህርቶች ያጠናቅቁ',
    viewCertificate: 'የምስክር ወረቀት ይመልከቱ',
    journeyComplete: 'ጉዞ ተጠናቅቋል!',
    finishLine: 'የማጠናቀቂያ መስመር',
    returnToDashboard: 'ወደ ዳሽቦርድ ተመለስ',
    completedLesson: 'ተጠናቅቋል',
    passedQuizScore: 'ፈተና ተሳክቷል · ነጥብ',
    lessonsCompletedOf: 'ትምህርቶች ተጠናቅቀዋል',

    // Quiz
    quizTitle: 'ፈተና',
    answered: 'ተመልሷል',
    answerAllToSubmit: 'ለማቅረብ ሁሉንም ይመልሱ',
    submitQuiz: 'ፈተና አቅርብ',
    submitting: 'በማቅረብ ላይ…',
    pleaseAnswerAll: 'እባክዎ ሁሉንም',
    remainingQuestions: 'ቀሪ ጥያቄዎችን ከማቅረቡ በፊት ይመልሱ።',
    questionRequiresAnswer: 'በዚህ ጥያቄ ምላሽ ያስፈልጋል።',
    reviewTitle: 'መቀመሪያ',
    passed: 'ተሳክቷል',
    didNotPass: 'አልተሳካም',
    correct: 'ትክክል',
    score: 'ነጥብ',
    passingScore: 'ያለፈ ነጥብ',
    yourAnswer: 'መልስዎ',
    correctAnswer: 'ትክክለኛ መልስ',
    goToNextLesson: 'ወደ ቀጣዩ ትምህርት ሂድ →',
    retakeQuiz: 'ፈተና ድገም',
    levelComplete: 'ደረጃ ተጠናቅቅ!',
    congratulations: 'እንኳን ደስ አለዎ!',
    levelCertificateMsg: 'በተሳካ ሁኔታ ያጠናቀቁት',
    levelCertificateMsg2: 'ደረጃ ሲሆን የምስክር ወረቀት ተሰጥቶዎታል።',
    viewMyCertificate: 'የምስክር ወረቀቴን ይመልከቱ',
    backToLevels2: 'ወደ ደረጃዎች ተመለስ',

    // Certificates
    achievements: 'ስካቶች',
    certificatesTitle: 'የምስክር ወረቀቶች',
    certSubtitle: 'ለማየት የምስክር ወረቀቱን ይንኩ። PDF ለማውረድ አውርድ ቁልፍን ይጠቀሙ።',
    earned: 'ተገኝ።',
    loadingCertificates: 'የምስክር ወረቀቶች በመጫን ላይ…',
    noCertificates: 'ምንም የምስክር ወረቀት አልተገኘም። የደረጃ ፈተናውን ለማለፍ ሁሉንም ትምህርቶች ያጠናቅቁ።',
    tapToOpen: 'ለመክፈት ይንኩ',
    issued: 'የተሰጠበት',
    downloading: 'በማውረድ ላይ…',
    downloadPdf: 'PDF አውርድ',

    // Notifications extra
    notificationsSubtitle: 'ማስጠንቀቂያዎችን እና ሪፖርቶችን ይከታተሉ',
    warningsTab: 'ማስጠንቀቂያዎች',
    reportsTab: 'ስለ እርስዎ ሪፖርቶች',
    noWarningsTitle: 'ምንም ማስጠንቀቂያ የለም',
    noWarningsText: 'ምንም ማስጠንቀቂያ የለዎትም። እያሻሻሉ ይቀጥሉ!',
    noReportsTitle: 'ምንም ሪፖርት የለም',
    noReportsText: 'ምንም ሙስሉ አልሪፖርተዎትም። ተሳካ የማህበረሰብ አባል ሁኑ!',
    adminWarning: 'የአደሚን ማስጠንቀቂያ',
    warningDisappears: 'ይህ ማስጠንቀቂያ ከ30 ቀናት በኋላ ይጠፋል።',
    reportFiled: 'ስለ እርስዎ ሪፖርት ቀርቧል',
    reason: 'ምክንያት',
    communityGuidelines: 'የማህበረሰብ መመሪያዎች',
    communityGuidelinesText: 'አክብሮታዊ ይሁኑ፣ ሌሎችን ይርዱ፣ የማህበረሰቡን ህጎች ይከተሉ።',
    needHelp: 'እርዳታ ይፈልጋሉ?',
    needHelpText: 'ስለ ማስጠንቀቂያ ወይም ሪፖርት ጥያቄ ካለዎ አስተዳዳሪ ያነጋግሩ።',
    justNow: 'ድሮ',
    minutesAgo: 'ደቂቃዎች በፊት',
    hoursAgo: 'ሰዓታወች በፊት',
    daysAgo: 'ቀናት በፊት',
    loadingNotifications: 'ማሳወቂያዎች በመጫን ላይ...',
    failedNotifications: 'ማሳወቂያዎችን መጫን አልተሳካም',

    // Levels extra
    unlockedLevelsDetermineCapacities: 'የተከፈቱ ደረጃዎች የበቃ ትምህርት አቅሞችን ይወስናሉ።',
    activeLevels: 'ንቁ ደረጃዎች',
    curriculumFlowTitle: 'የትምህርት ፍሰት',
    levelCompass: 'ደረጃ መናኪያ',
    completeAllLessons: 'የቀደሙ ደረጃ ትምህርቶችን እና ፈተናዎችን ታጠናቅቁ',
    passPreviousQuiz: 'ለመክፈት የቀደሙ ደረጃ ፈተና ያልፉ',

    // Progress extra
    skillPlan: 'የንቡሮ ዕቅድ',
    exams: 'ፈተናዎች',
    overview: 'ዘርዝሮ',
    times: 'ጊዜ',
    quizzes: 'ፈተናዎች',
    days_unit: 'ቀናት',
    grammarQuote: '"ሰዋሱወን ማወቅ ወደ ነፃነት የሚወስደው መንገድ ነው።"',
    exploreChapters: 'የምዕራፍ ማስመሪያዎችን እና ይሬዴ ጥያቄዎችን አሁን ይጎብኙ።',
    chapter03: 'ምዕራፍ 03: የግል ጥናት መዝገቦች',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const { user } = useAuth()
  const lang = user?.language || 'en'

  const t = useCallback((key) => translations[lang]?.[key] ?? translations.en[key] ?? key, [lang])

  const toggleLanguage = useCallback(async () => {
    const newLang = lang === 'en' ? 'am' : 'en'
    try {
      await api.patch('/users/profile/', { language: newLang })
      // Reload the page so AuthContext re-fetches user with new language
      window.location.reload()
    } catch {
      // silently ignore
    }
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
