import { createContext, useContext, useCallback } from 'react'
import { useAuth } from './AuthContext.jsx'
import api from '../api/client.js'

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    levels: 'Levels',
    curriculum: 'Curriculum',
    progress: 'Progress',
    certificates: 'Certificates',
    community: 'Community',
    notifications: 'Notifications',
    profile: 'Profile',
    logout: 'Logout',

    // Dashboard
    curriculumFlow: 'Curriculum Flow',
    learner: 'Learner',
    progressTracker: 'Progress Tracker',
    welcomeBack: 'Welcome back',
    continueJourney: 'Continue your learning journey. Keep improving step by step.',
    completedLessons: 'Completed Lessons',
    successfulQuizzes: 'Successful Quizzes',
    failedQuizzes: 'Failed Quizzes',
    avgQuizScore: 'Avg Quiz Score',
    streak: 'Streak',
    recentActivities: 'Recent Activities',
    viewAll: 'View All →',
    noRecentActivity: 'No recent activity yet. Start learning!',
    recommended: 'Recommended',
    completeForRecommendations: 'Complete lessons to get recommendations.',
    quickActions: 'Quick Actions',
    continueLearning: '📖 Continue Learning',
    viewProgress: '📊 View Progress',
    retakeLevel: '🔄 Retake Level',
    day: 'day',
    days: 'days',

    // Levels
    structuredPathway: 'Structured Pathway',
    proficiencyLevels: 'Proficiency Levels',
    academicProgress: 'Academic Progress',
    unlockedLevels: 'Active Levels',
    pathwayMetrics: 'Pathway Metrics',
    chapter: 'Chapter',
    locked: 'Locked',
    active: 'Active',
    lockedContent: 'Locked Content',
    beginJourney: 'Begin Journey',
    takeLevelQuiz: 'Take Level Quiz',
    noLevelsFound: 'No levels found',

    // Courses
    availableModules: 'Available Modules',
    selectModule: 'Select a module to start learning',
    backToLevels: 'Back to Levels',
    viewLessons: 'View Lessons',
    noModules: 'No modules available',

    // Lessons
    yourLearningPath: 'Your Learning Path',
    workThroughLessons: 'Work through each lesson in order — unlock the next as you complete them.',
    backToModules: '← Back to Modules',
    open: 'Open',
    completed: 'Completed',
    noLessons: 'No lessons in this module yet',

    // Lesson Detail
    lesson: 'Lesson',
    backToModule: '← Back to module',
    markComplete: 'Mark as complete',
    saving: 'Saving…',
    takeQuiz: 'Take quiz →',
    askAiTutor: 'Ask AI Tutor',
    closeTutor: 'Close Tutor',
    askMeAnything: 'Ask me anything about this lesson!',
    thinking: 'Thinking…',
    send: 'Send',
    askQuestion: 'Ask a question…',

    // Progress
    yourLearningProgress: 'Your Learning Progress',
    trackYourJourney: 'Track your journey, monitor your habits, and record your achievements.',
    yourCurrentLevel: 'Your Current Level',
    passedQuizzes: 'Passed Quizzes',
    successRate: 'Success Rate',
    streakDays: 'Streak Days',
    quizPerformance: 'Quiz Performance',
    totalQuizAttempts: 'Total Quiz Attempts',
    quizSuccessRate: 'Quiz Success Rate',
    takeMoreQuizzes: 'Take More Quizzes',
    learningSummary: 'Learning Summary',
    lessonsCompleted: 'Lessons Completed',
    studyStreak: 'Study Streak',
    readyForNewLessons: 'Ready to start new lessons?',
    exploreNow: 'Start Now →',

    // Community
    communityHub: 'Community Hub',
    connectShareLearn: 'Connect, share, and learn together',
    newDiscussion: 'New Discussion',
    reportsAgainstMe: 'Reports Against Me',
    noPostsYet: 'No posts yet. Be the first to start a discussion!',
    comments: 'comments',
    postReply: 'Post Reply',
    writeReply: 'Write a reply...',
    createDiscussion: 'Create New Discussion',
    title: 'Title',
    content: 'Content',
    cancel: 'Cancel',
    post: 'Post Discussion',
    edit: 'Edit',
    delete: 'Delete',
    report: 'Report',

    // Notifications
    notifications_title: 'Notifications',
    stayUpdated: 'Stay updated with warnings and reports',
    warnings: 'Warnings',
    reportsAgainstYou: 'Reports Against You',
    noWarnings: 'No Warnings',
    noWarningsMsg: 'You have no warnings. Keep up the good work!',

    // Profile
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    courseProgress: 'Course Progress',
    noProgressYet: 'No course progress yet. Start learning to see your progress!',
    quizAverage: 'Quiz Average',
    currentLevel: 'Current Level',

    // Common
    loading: 'Loading...',
    retry: 'Try Again',
    save: 'Save Changes',
    forgotPassword: 'Forgot Password?',
    updatePassword: 'Update Password',
    loadingProfile: 'Loading profile...',
    failedProfile: 'Failed to load profile',
    lessonsUnit: 'lessons',
    // Level name translations
    levelName_Beginner: 'Beginner',
    levelName_Intermediate: 'Intermediate',
    levelName_Advanced: 'Advanced',
    // Curriculum
    curriculumModules: 'Curriculum / Modules',
    moduleLesson: 'Module / Lesson',
    curriculumRoadmap: 'Learning Roadmap',
    fullLearningPath: 'Your Full Learning Path',
    curriculumSubtitle: 'Every level, module, and lesson — your complete journey from start to certificate.',
    overallProgress: 'Overall Progress',
    noCurriculum: 'No curriculum available',
    checkBackSoon: 'Check back soon.',
    levelLabel: 'Level',
    moduleLabel: 'Module',
    inProgress: 'In Progress',
    completedBadge: 'Completed',
    quizBadge: 'Quiz',
    doneBadge: 'Done',
    readyBadge: 'Ready',
    certUnlocked: 'Certificate Unlocked!',
    levelCertLabel: 'Level Certificate',
    completeAllToUnlock: 'Complete all lessons to unlock',
    viewCertificate: 'View Certificate',
    journeyComplete: 'Journey Complete!',
    finishLine: 'Finish Line',
    // Quiz
    quizTitle: 'Quiz',
    answered: 'answered',
    answerAllToSubmit: 'Answer all questions to submit',
    submitQuiz: 'Submit quiz',
    submitting: 'Submitting…',
    pleaseAnswerAll: 'Please answer all',
    remainingQuestions: 'remaining question(s) before submitting.',
    questionRequiresAnswer: 'This question requires an answer.',
    reviewTitle: 'Review',
    passed: 'Passed',
    didNotPass: 'Did not pass',
    correct: 'correct',
    score: 'Score',
    passingScore: 'Passing score',
    yourAnswer: 'Your answer',
    correctAnswer: 'Correct answer',
    goToNextLesson: 'Go to Next Lesson →',
    retakeQuiz: 'Retake Quiz',
    backToModule: '← Back to module',
    levelComplete: 'Level Complete!',
    congratulations: 'Congratulations!',
    levelCertificateMsg: 'You have successfully completed the',
    levelCertificateMsg2: 'level and earned a certificate.',
    viewMyCertificate: '🏅 View My Certificate',
    backToLevels2: 'Back to Levels',

    // Certificates
    achievements: 'Achievements',
    certificatesTitle: 'Certificates',
    certSubtitle: 'Tap a certificate to view, or use the Download button to save a PDF.',
    earned: 'earned',
    loadingCertificates: 'Loading certificates…',
    noCertificates: 'No certificates earned yet. Complete a level to unlock your first certificate.',
    tapToOpen: 'Tap to open',
    issued: 'Issued',
    downloading: 'Downloading…',
    downloadPdf: 'Download PDF',

    // Notifications extra
    notificationsSubtitle: 'Stay updated with warnings and reports',
    warningsTab: 'Warnings',
    reportsTab: 'Reports Against You',
    noWarningsTitle: 'No Warnings',
    noWarningsText: 'You have no warnings. Keep up the good work!',
    noReportsTitle: 'No Reports',
    noReportsText: 'No one has reported you. Keep being a positive community member!',
    adminWarning: 'Admin Warning',
    warningDisappears: 'This warning will disappear automatically after 30 days.',
    reportFiled: 'Report Filed Against You',
    reason: 'Reason',
    communityGuidelines: 'Community Guidelines',
    communityGuidelinesText: 'Be respectful, help others, and follow our community rules to maintain a positive learning environment.',
    needHelp: 'Need Help?',
    needHelpText: 'If you have questions about a warning or report, please contact an admin.',
    justNow: 'Just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    loadingNotifications: 'Loading notifications...',
    failedNotifications: 'Failed to load notifications',

    // Levels extra
    structuredPathway: 'Structured Pathway',
    proficiencyLevels: 'Proficiency Levels',
    academicProgress: 'Academic Progress',
    unlockedLevelsDetermineCapacities: 'Unlocked levels determine active learning capacities.',
    pathwayMetrics: 'Pathway Metrics',
    activeLevels: 'Active Levels',
    curriculumFlowTitle: 'Curriculum Flow',
    chapter: 'Chapter',
    levelCompass: 'Level Compass',
    lockedContent: 'Locked Content',
    beginJourney: 'Begin Journey',
    takeLevelQuiz: 'Take Level Quiz',
    completeAllLessons: 'Complete all lessons & quizzes in the previous level first',
    passPreviousQuiz: "Pass the previous level's final quiz to unlock",

    // Progress extra
    skillPlan: 'Skill Plan',
    exams: 'Exams',
    overview: 'Overview',
    times: 'times',
    quizzes: 'quizzes',
    days_unit: 'days',
    grammarQuote: '"Knowing grammar is the path to freedom."',
    exploreChapters: 'Explore chapter courses and interactive tests now.',
    chapter03: 'Chapter 03: Personal Study Records',

    returnToDashboard: 'Return to Dashboard',
    completedLesson: 'Completed',
    passedQuizScore: 'Passed quiz · Score',
    lessonsCompletedOf: 'lessons completed',

    // Login & Register
    helloAgain: 'Hello again',
    signInToKeepClimbing: 'Sign in to keep climbing.',
    usernameOrEmail: 'Username or Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    invalidCredentials: 'Invalid username/email or password.',
    noActiveAccount: 'No active account was found. If you have already registered, please',
    contactUs: 'Contact Us',
    forAssistance: 'for assistance.',
    newHere: 'New here?',
    createAccount: 'Create an account',
    createYourAccount: 'Create your account',
    startWithPlacementTest: 'Start with a quick placement test.',
    fullName: 'Full Name',
    email: 'Email',
    gender: 'Gender',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    confirmPassword: 'Confirm Password',
    passwordStrength: 'Password Strength',
    weak: 'Weak',
    fair: 'Fair',
    good: 'Good',
    strong: 'Strong',
    passwordsMustMatch: 'Passwords do not match',
    passwordRequirements: 'Password must be 8+ chars with uppercase, lowercase, and number',
    selectGenderError: 'Please select gender',
    pwMinLength: 'At least 8 characters',
    pwUppercase: 'At least 1 uppercase letter',
    pwLowercase: 'At least 1 lowercase letter',
    pwNumber: 'At least 1 number',
    username: 'Username',
    backToHome: '← Back to Home',
    invalidFullName: 'Full name can only contain letters and spaces.',
    invalidUsername: 'Username can only contain letters and numbers.',
    useAnotherUsername: 'Use a different username',
    registerError: 'Could not register',
    register: 'Register',
    registering: 'Registering…',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',

    // Home Page
    aboutEthsl: 'About ETHSL',
    whatIsEthsl: 'What is ETHSL?',
    ethslDescription: 'ETHSL (Ethiopian Sign Language Tutor) is an innovative learning platform designed to make Ethiopian Sign Language education accessible, engaging, and effective for everyone.',
    learnEthiopianSignLanguage: 'Learn Ethiopian Sign Language',
    theModernWay: 'the modern way.',
    structuredVisualLearning: 'A structured, visual learning platform that helps learners master Ethiopian Sign Language through engaging lessons, assessments, and guided progression from beginner to advanced levels.',
    getStarted: 'Get Started →',
    signUp: 'Sign Up',
    dashboard: 'Dashboard',
    continueL: 'Continue Learning →',
    learnEsl: 'Learn Ethiopian Sign Language visually',

    // Home Page extra
    homeAbout: 'About',
    homeWhyEthsl: 'Why ETHSL',
    homeFeatures: 'Features',
    homeHowItWorks: 'How It Works',
    homeBenefits: 'Benefits',
    homeFaq: 'FAQ',
    homeContact: 'Contact',
    homeLogin: 'Login',
    homeRegister: 'Register',
    homeGetStarted: 'Get Started →',
    homeSignIn: 'Sign In',
    homeHeroTitle: 'Learn Ethiopian Sign Language',
    homeHeroEm: 'the modern way.',
    homeHeroSubtitle: 'A structured, visual learning platform that helps learners master Ethiopian Sign Language through engaging lessons, assessments, and guided progression from beginner to advanced levels.',
    homeWhatIsEthsl: 'What is ETHSL?',
    homeAboutDesc: 'ETHSL (Ethiopian Sign Language Tutor) is an innovative learning platform designed to make Ethiopian Sign Language education accessible, engaging, and effective for everyone. Through structured lessons, visual demonstrations, and guided learning pathways, users can build communication skills at their own pace.',
    homeBuiltForAll: 'Built for Everyone',
    homeBuiltForAllDesc: 'Students, teachers, parents, professionals, and anyone interested in inclusive communication can benefit from learning Ethiopian Sign Language through ETHSL.',
    homeWhyChoose: 'Why Choose ETHSL?',
    homeVisualLearning: 'Visual Learning',
    homeVisualDesc: 'Learn signs through clear visual demonstrations that make learning intuitive and memorable.',
    homeStructuredLevels: 'Structured Levels',
    homeStructuredDesc: 'Progress through carefully designed levels that help build confidence and mastery over time.',
    homeProgressTracking: 'Progress Tracking',
    homeProgressDesc: 'Monitor lesson completion, quiz results, and learning achievements throughout your journey.',
    homePlatformFeatures: 'Platform Features',
    homeVideoLessons: 'Video-Based Lessons',
    homeInteractiveAssessments: 'Interactive Assessments',
    homeLevelUnlock: 'Level Unlock System',
    homeLessonDiscovery: 'Lesson Discovery',
    homeAccessibleLearning: 'Accessible Learning',
    homeHowTitle: 'How It Works',
    homeStep1: 'Create an Account',
    homeStep2: 'Take Placement Assessment',
    homeStep3: 'Start Learning Lessons',
    homeStep4: 'Track Progress & Improve',
    homeInclusiveComm: 'Inclusive Communication',
    homeInclusiveDesc: 'Ethiopian Sign Language helps bridge communication gaps and promotes accessibility for individuals with hearing impairments and the wider community.',
    homeWhyLearn: 'Why Learn Ethiopian Sign Language?',
    homeWhyLearnDesc: 'Learning sign language strengthens communication, promotes inclusion, supports equal opportunities, and helps create a society where everyone can participate and connect effectively.',
    homeFaqTitle: 'Frequently Asked Questions',
    homeFaq1Q: 'Do I need prior experience?',
    homeFaq1A: 'No. ETHSL is designed for beginners and learners of all skill levels.',
    homeFaq2Q: 'Is the platform free?',
    homeFaq2A: 'Yes. Learners can access educational resources and begin learning without cost.',
    homeFaq3Q: 'Can I learn on mobile devices?',
    homeFaq3A: 'Absolutely. ETHSL works on desktops, tablets, and smartphones.',
    homeContactTitle: 'Contact Us',
    homeContactDesc: 'Have questions, suggestions, or feedback?',
    homeContactDesc2: "We'd love to hear from you.",
    homeLangToggle: 'አማርኛ',
  },

  am: {
    // Nav
    dashboard: 'ዳሽቦርድ',
    levels: 'ደረጃዎች',
    curriculum: 'ስርዓተ ትምህርት',
    progress: 'እድገት',
    certificates: 'የምስክር ወረቀቶች',
    community: 'ማህበረሰብ',
    notifications: 'ማሳወቂያዎች',
    profile: 'መገለጫ',
    logout: 'ውጣ',

    // Dashboard
    curriculumFlow: 'የትምህርት ፍሰት',
    learner: 'ተማሪ',
    progressTracker: 'የእድገት መቆጣጠሪያ',
    welcomeBack: 'እንኳን ደህና መጡ',
    continueJourney: 'የትምህርት ጉዞዎን ይቀጥሉ። እርምጃ በእርምጃ እያሻሻሉ ይሂዱ።',
    completedLessons: 'የተጠናቀቁ ትምህርቶች',
    successfulQuizzes: 'የተሳኩ ፈተናዎች',
    failedQuizzes: 'ያልተሳኩ ፈተናዎች',
    avgQuizScore: 'አማካይ የፈተና ነጥብ',
    streak: 'ተከታታይ ቀናት',
    recentActivities: 'የቅርብ ጊዜ እንቅስቃሴዎች',
    viewAll: 'ሁሉንም ይዩ →',
    noRecentActivity: 'እስካሁን ምንም እንቅስቃሴ የለም። መማር ይጀምሩ!',
    recommended: 'የሚመከር',
    completeForRecommendations: 'ምክሮችን ለማግኘት ትምህርቶችን ያጠናቅቁ።',
    quickActions: 'ፈጣን እርምጃዎች',
    continueLearning: '📖 መማርን ይቀጥሉ',
    viewProgress: '📊 እድገት ይመልከቱ',
    retakeLevel: '🔄 ደረጃ ይድገሙ',
    day: 'ቀን',
    days: 'ቀናት',

    // Levels
    structuredPathway: 'የተደራጀ መንገድ',
    proficiencyLevels: 'የብቃት ደረጃዎች',
    academicProgress: 'የትምህርት እድገት',
    unlockedLevels: 'ንቁ ደረጃዎች',
    pathwayMetrics: 'የመንገድ መለኪያዎች',
    chapter: 'ምዕራፍ',
    locked: 'ተቆልፏል',
    active: 'ንቁ',
    lockedContent: 'ተቆልፏል',
    beginJourney: 'ጉዞ ይጀምሩ',
    takeLevelQuiz: 'የደረጃ ፈተና ይውሰዱ',
    noLevelsFound: 'ምንም ደረጃ አልተገኘም',

    // Courses
    availableModules: 'ሞጁሎች',
    selectModule: 'ለመማር ሞጁል ይምረጡ',
    backToLevels: 'ወደ ደረጃዎች ተመለስ',
    viewLessons: 'ትምህርቶችን ይዩ',
    noModules: 'ምንም ሞጁሎች የሉም',

    // Lessons
    yourLearningPath: 'የትምህርት መንገድዎ',
    workThroughLessons: 'እያንዳንዱን ትምህርት በቅደም ተከተል ይስሩ — ሲጠናቀቁ ቀጣዩን ይክፈቱ።',
    backToModules: '← ወደ ሞጁሎች ተመለስ',
    open: 'ክፍት',
    completed: 'ተጠናቅቋል',
    noLessons: 'እስካሁን ምንም ትምህርቶች የሉም',

    // Lesson Detail
    lesson: 'ትምህርት',
    backToModule: '← ወደ ሞጁሉ ተመለስ',
    markComplete: 'እንደተጠናቀቀ ምልክት አድርግ',
    saving: 'በመቀመጥ ላይ…',
    takeQuiz: 'ፈተና ውሰድ →',
    askAiTutor: 'AI አስተማሪን ይጠይቁ',
    closeTutor: 'አስተማሪ ዝጋ',
    askMeAnything: 'ስለዚህ ትምህርት ማንኛውም ነገር ይጠይቁኝ!',
    thinking: 'በማሰብ ላይ…',
    send: 'ላክ',
    askQuestion: 'ጥያቄ ይጠይቁ…',

    // Progress
    yourLearningProgress: 'የትምህርት እድገትዎ',
    trackYourJourney: 'ጉዞዎን ይከታተሉ፣ ልምዶቻቸውን ይቆጣጠሩ፣ ስኬቶቻቸውን ይመዝግቡ።',
    yourCurrentLevel: 'የአሁን ደረጃዎ',
    passedQuizzes: 'ያለፉ ፈተናዎች',
    successRate: 'ስኬት ደረጃ',
    streakDays: 'ተከታታይ ቀናት',
    quizPerformance: 'የፈተና አፈፃፀም',
    totalQuizAttempts: 'ጠቅላላ የፈተና ሙከራዎች',
    quizSuccessRate: 'የፈተና ስኬት ደረጃ',
    takeMoreQuizzes: 'ተጨማሪ ፈተናዎች ውሰዱ',
    learningSummary: 'የትምህርት ማጠቃለያ',
    lessonsCompleted: 'የተጠናቀቁ ትምህርቶች',
    studyStreak: 'የጥናት ተከታታይ ቀናት',
    readyForNewLessons: 'አዲስ ትምህርቶች ለመጀመር ዝግጁ ነዎት?',
    exploreNow: 'አሁን ይጀምሩ →',

    // Community
    communityHub: 'የማህበረሰብ ማዕከል',
    connectShareLearn: 'ተገናኙ፣ ያካፍሉ፣ አብረው ይማሩ',
    newDiscussion: 'አዲስ ውይይት',
    reportsAgainstMe: 'ስለ እኔ ሪፖርቶች',
    noPostsYet: 'እስካሁን ምንም ልጥፍ የለም። የመጀመሪያው ውይይት ይጀምሩ!',
    comments: 'አስተያየቶች',
    postReply: 'ምላሽ ይስጡ',
    writeReply: 'ምላሽ ይጻፉ...',
    createDiscussion: 'አዲስ ውይይት ፍጠር',
    title: 'ርዕስ',
    content: 'ይዘት',
    cancel: 'ሰርዝ',
    post: 'ውይይት ይለጥፉ',
    edit: 'አስተካክል',
    delete: 'ሰርዝ',
    report: 'ሪፖርት',

    // Notifications
    notifications_title: 'ማሳወቂያዎች',
    stayUpdated: 'ማስጠንቀቂያዎችን እና ሪፖርቶችን ይከታተሉ',
    warnings: 'ማስጠንቀቂያዎች',
    reportsAgainstYou: 'ስለ እርስዎ ሪፖርቶች',
    noWarnings: 'ምንም ማስጠንቀቂያ የለም',
    noWarningsMsg: 'ምንም ማስጠንቀቂያ የለዎትም። እያሻሻሉ ይቀጥሉ!',

    // Profile
    editProfile: 'መገለጫ አስተካክል',
    changePassword: 'የይለፍ ቃል ቀይር',
    courseProgress: 'የኮርስ እድገት',
    noProgressYet: 'እስካሁን ምንም የኮርስ እድገት የለም። ለማየት መማር ይጀምሩ!',
    quizAverage: 'አማካይ ፈተና',
    currentLevel: 'የአሁን ደረጃ',

    // Common
    loading: 'በመጫን ላይ...',
    retry: 'እንደገና ሞክር',
    save: 'ለውጦችን አስቀምጥ',
    forgotPassword: 'የይለፍ ቃል ረሳኸው?',
    updatePassword: 'የይለፍ ቃሉን አዘምን',
    loadingProfile: 'መገለጫ በመጫን ላይ...',
    failedProfile: 'መገለጫ መጫን አልተሳካም',
    lessonsUnit: 'ትምህርቶች',
    // Level name translations
    levelName_Beginner: 'ጀማሪ',
    levelName_Intermediate: 'መካከለኛ',
    levelName_Advanced: 'ከፍተኛ',
    // Curriculum
    curriculumModules: 'ስርዓተ ትምህርት / ሞጁሎች',
    moduleLesson: 'ሞጁል / ትምህርት',
    curriculumRoadmap: 'የትምህርት ካርታ',
    fullLearningPath: 'ሙሉ የትምህርት መንገድዎ',
    curriculumSubtitle: 'እያንዳንዱ ደረጃ፣ ሞጁል እና ትምህርት — ከጅምር እስከ የምስክር ወረቀት ሙሉ ጉዞዎ።',
    overallProgress: 'አጠቃላይ እድገት',
    noCurriculum: 'ምንም ስርዓተ ትምህርት የለም',
    checkBackSoon: 'በቅርቡ ይመልሱ።',
    levelLabel: 'ደረጃ',
    moduleLabel: 'ሞጁል',
    inProgress: 'በሂደት ላይ',
    completedBadge: 'ተጠናቅቋል',
    quizBadge: 'ፈተና',
    doneBadge: 'ተጠናቅቋል',
    readyBadge: 'ዝግጁ',
    certUnlocked: 'የምስክር ወረቀት ተከፈተ!',
    levelCertLabel: 'የደረጃ የምስክር ወረቀት',
    completeAllToUnlock: 'ለመክፈት ሁሉንም ትምህርቶች ያጠናቅቁ',
    viewCertificate: 'የምስክር ወረቀት ይመልከቱ',
    journeyComplete: 'ጉዞ ተጠናቅቋል!',
    finishLine: 'የማጠናቀቂያ መስመር',
    returnToDashboard: 'ወደ ዳሽቦርድ ተመለስ',
    completedLesson: 'ተጠናቅቋል',
    passedQuizScore: 'ፈተና ተሳክቷል · ነጥብ',
    lessonsCompletedOf: 'ትምህርቶች ተጠናቅቀዋል',

    // Quiz
    quizTitle: 'ፈተና',
    answered: 'ተመልሷል',
    answerAllToSubmit: 'ለማቅረብ ሁሉንም ይመልሱ',
    submitQuiz: 'ፈተና አቅርብ',
    submitting: 'በማቅረብ ላይ…',
    pleaseAnswerAll: 'እባክዎ ሁሉንም',
    remainingQuestions: 'ቀሪ ጥያቄዎችን ከማቅረቡ በፊት ይመልሱ።',
    questionRequiresAnswer: 'በዚህ ጥያቄ ምላሽ ያስፈልጋል።',
    reviewTitle: 'መቀመሪያ',
    passed: 'ተሳክቷል',
    didNotPass: 'አልተሳካም',
    correct: 'ትክክል',
    score: 'ነጥብ',
    passingScore: 'ያለፈ ነጥብ',
    yourAnswer: 'መልስዎ',
    correctAnswer: 'ትክክለኛ መልስ',
    goToNextLesson: 'ወደ ቀጣዩ ትምህርት ሂድ →',
    retakeQuiz: 'ፈተና ድገም',
    levelComplete: 'ደረጃ ተጠናቅቅ!',
    congratulations: 'እንኳን ደስ አለዎ!',
    levelCertificateMsg: 'በተሳካ ሁኔታ ያጠናቀቁት',
    levelCertificateMsg2: 'ደረጃ ሲሆን የምስክር ወረቀት ተሰጥቶዎታል።',
    viewMyCertificate: 'የምስክር ወረቀቴን ይመልከቱ',
    backToLevels2: 'ወደ ደረጃዎች ተመለስ',

    // Certificates
    achievements: 'ስካቶች',
    certificatesTitle: 'የምስክር ወረቀቶች',
    certSubtitle: 'ለማየት የምስክር ወረቀቱን ይንኩ። PDF ለማውረድ አውርድ ቁልፍን ይጠቀሙ።',
    earned: 'ተገኝ።',
    loadingCertificates: 'የምስክር ወረቀቶች በመጫን ላይ…',
    noCertificates: 'ምንም የምስክር ወረቀት አልተገኘም። የደረጃ ፈተናውን ለማለፍ ሁሉንም ትምህርቶች ያጠናቅቁ።',
    tapToOpen: 'ለመክፈት ይንኩ',
    issued: 'የተሰጠበት',
    downloading: 'በማውረድ ላይ…',
    downloadPdf: 'PDF አውርድ',

    // Notifications extra
    notificationsSubtitle: 'ማስጠንቀቂያዎችን እና ሪፖርቶችን ይከታተሉ',
    warningsTab: 'ማስጠንቀቂያዎች',
    reportsTab: 'ስለ እርስዎ ሪፖርቶች',
    noWarningsTitle: 'ምንም ማስጠንቀቂያ የለም',
    noWarningsText: 'ምንም ማስጠንቀቂያ የለዎትም። እያሻሻሉ ይቀጥሉ!',
    noReportsTitle: 'ምንም ሪፖርት የለም',
    noReportsText: 'ምንም ሙስሉ አልሪፖርተዎትም። ተሳካ የማህበረሰብ አባል ሁኑ!',
    adminWarning: 'የአደሚን ማስጠንቀቂያ',
    warningDisappears: 'ይህ ማስጠንቀቂያ ከ30 ቀናት በኋላ ይጠፋል።',
    reportFiled: 'ስለ እርስዎ ሪፖርት ቀርቧል',
    reason: 'ምክንያት',
    communityGuidelines: 'የማህበረሰብ መመሪያዎች',
    communityGuidelinesText: 'አክብሮታዊ ይሁኑ፣ ሌሎችን ይርዱ፣ የማህበረሰቡን ህጎች ይከተሉ።',
    needHelp: 'እርዳታ ይፈልጋሉ?',
    needHelpText: 'ስለ ማስጠንቀቂያ ወይም ሪፖርት ጥያቄ ካለዎ አስተዳዳሪ ያነጋግሩ።',
    justNow: 'ድሮ',
    minutesAgo: 'ደቂቃዎች በፊት',
    hoursAgo: 'ሰዓታወች በፊት',
    daysAgo: 'ቀናት በፊት',
    loadingNotifications: 'ማሳወቂያዎች በመጫን ላይ...',
    failedNotifications: 'ማሳወቂያዎችን መጫን አልተሳካም',

    // Levels extra
    unlockedLevelsDetermineCapacities: 'የተከፈቱ ደረጃዎች የበቃ ትምህርት አቅሞችን ይወስናሉ።',
    activeLevels: 'ንቁ ደረጃዎች',
    curriculumFlowTitle: 'የትምህርት ፍሰት',
    levelCompass: 'ደረጃ መናኪያ',
    completeAllLessons: 'የቀደሙ ደረጃ ትምህርቶችን እና ፈተናዎችን ታጠናቅቁ',
    passPreviousQuiz: 'ለመክፈት የቀደሙ ደረጃ ፈተና ያልፉ',

    // Progress extra
    skillPlan: 'የንቡሮ ዕቅድ',
    exams: 'ፈተናዎች',
    overview: 'ዘርዝሮ',
    times: 'ጊዜ',
    quizzes: 'ፈተናዎች',
    days_unit: 'ቀናት',
    grammarQuote: '"ሰዋሱወን ማወቅ ወደ ነፃነት የሚወስደው መንገድ ነው።"',
    exploreChapters: 'የምዕራፍ ማስመሪያዎችን እና ይሬዴ ጥያቄዎችን አሁን ይጎብኙ።',
    chapter03: 'ምዕራፍ 03: የግል ጥናት መዝገቦች',

    // Login & Register
    helloAgain: 'እንደገና ሰላም',
    signInToKeepClimbing: 'ለመቀጠል ይግቡ።',
    usernameOrEmail: 'ተጠቃሚ ስም ወይም ኢሜይል',
    password: 'የይለፍ ቃል',
    signIn: 'ይግቡ',
    signingIn: 'በመግባት ላይ…',
    invalidCredentials: 'ጋር ተጠቃሚ ስም/ኢሜይል ወይም የይለፍ ቃል ብዙ የለም።',
    noActiveAccount: 'ምንም ንቁ ሂሳብ አልተገኘም። ቀድሞ ከተመዘገቡ እባክዎ',
    contactUs: 'ያነጋግሩን',
    forAssistance: 'ለእርዳታ።',
    newHere: 'ጀማሪ ነዎት?',
    createAccount: 'ሂሳብ ፍጠር',
    createYourAccount: 'ሂሳብህ ፍጠር',
    startWithPlacementTest: 'በፈጣን ደረጃ ሙከራ ይጀምሩ።',
    fullName: 'ሙሉ ስም',
    email: 'ኢሜይል',
    gender: 'ጾታ',
    selectGender: 'ጾታ ይምረጡ',
    male: 'ወንድ',
    female: 'ሴት',
    confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
    passwordStrength: 'የይለፍ ቃል ጥንካሬ',
    weak: 'ደካማ',
    fair: 'ጥሩ',
    good: 'ጥሩ',
    strong: 'ጠንካራ',
    passwordsMustMatch: 'የይለፍ ቃሎች አይዛመዱም',
    passwordRequirements: 'የይለፍ ቃል 8 ገበታ ወይም ከዚያ በላይ መስሪያ፣ ዓ፣ ንዑስ፣ እና ቁጥር መሆን አለበት',
    selectGenderError: 'እባክዎ ጾታ ይምረጡ',
    pwMinLength: 'ቢያንስ 8 ገበታ',
    pwUppercase: 'ቢያንስ 1 ትልቅ ፊደል',
    pwLowercase: 'ቢያንስ 1 ንዑስ ፊደል',
    pwNumber: 'ቢያንስ 1 ቁጥር',
    invalidFullName: 'ሙሉ ስም ፊደል እና ቦታዎች ብቻ ሊይዝ ይችላል።',
    invalidUsername: 'ተጠቃሚ ስም ፊደል እና ቁጥሮች ብቻ ሊይዝ ይችላል።',
    useAnotherUsername: 'ሌላ ተጠቃሚ ስም ይጠቀሙ',
    registerError: 'መመዝገብ አልተሳካም',
    register: 'ይመዝገቡ',
    registering: 'በመመዝገብ ላይ…',
    alreadyHaveAccount: 'ቀድሞ ሂሳብ ያለህ?',
    signInHere: 'እዚህ ይግቡ',

    // Home Page
    aboutEthsl: 'ስለ ETHSL',
    whatIsEthsl: 'ETHSL ምንድነው?',
    ethslDescription: 'ETHSL (Ethiopian Sign Language Tutor) የኢትዮጵያ የምልክት ቋንቋ ትምህርትን ለሁሉም ሰው ተደራሽ፣ አስገራሚ እና ውጤታማ ለማድረግ የተነደፈ ፈጠራ ዋንጫ ነው።',
    learnEthiopianSignLanguage: 'የኢትዮጵያ የምልክት ቋንቋ ይማሩ',
    theModernWay: 'ዘመናዊ መንገድ።',
    structuredVisualLearning: 'መዋቅርያዊ, ገላጭ የመማር ዋንጫ በማመልከቻ ትምህርቶች, ግምገማዎች, እና ስር ደረጃ ከጀማሪ ወደ ጎበጣ ደረጃ የኢትዮጵያ የምልክት ቋንቋ ለማስተማር የተነደፈ።',
    getStarted: 'ይጀምሩ →',
    signUp: 'ይመዝገቡ',
    dashboard: 'ዳሽቦርድ',
    continueL: 'መማርን ይቀጥሉ →',
    learnEsl: 'የኢትዮጵያ የምልክት ቋንቋ ነቢርነት ይማሩ',

    // Home Page extra
    homeAbout: 'ስለ',
    homeWhyEthsl: 'ለምን ETHSL',
    homeFeatures: 'ባህሪዎች',
    homeHowItWorks: 'እንዴት ይሠራል',
    homeBenefits: 'ጥቅሞች',
    homeFaq: 'ፍ.ጎ.ሙ',
    homeContact: 'ያናግሩን',
    homeLogin: 'ይግቡ',
    homeRegister: 'ይመዝገቡ',
    homeGetStarted: 'ይጀምሩ →',
    homeSignIn: 'ይግቡ',
    homeHeroTitle: 'የኢትዮጵያ የምልክት ቋንቋ ይማሩ',
    homeHeroEm: 'ዘመናዊ መንገድ።',
    homeHeroSubtitle: 'መዋቅርያዊ, ገላጭ የመማር ዋንጫ በማመልከቻ ትምህርቶች, ግምገማዎች, እና ስር ደረጃ ከጀማሪ ወደ ጎበጣ ደረጃ የኢትዮጵያ የምልክት ቋንቋ ለማስተማር የተነደፈ።',
    homeWhatIsEthsl: 'ETHSL ምንድነው?',
    homeAboutDesc: 'ETHSL (Ethiopian Sign Language Tutor) የኢትዮጵያ የምልክት ቋንቋ ትምህርትን ለሁሉም ሰው ተደራሽ፣ አስገራሚ እና ውጤታማ ለማድረግ የተነደፈ ፈጠራ ዋንጫ ነው።',
    homeBuiltForAll: 'ለሁሉም የተገነባ',
    homeBuiltForAllDesc: 'ተማሪዎች፣ አስተማሪዎች፣ ወላጆች, ሙያተኞች, እና በሚያገናኙት ግንኙነት ላይ ፍላጎት ያላቸው ማንም ሰው ETHSL በኩል ሊጠቀሙ ይችላሉ።',
    homeWhyChoose: 'ለምን ETHSL ይምረጡ?',
    homeVisualLearning: 'ነቢር ማመልከቻ',
    homeVisualDesc: 'ምልክቶችን በግልጽ ምስላዊ ሰቢካዎች በኩል ይማሩ።',
    homeStructuredLevels: 'መዋቅርያዊ ደረጃዎች',
    homeStructuredDesc: 'በጥንቃቄ የተነደፈ ደረጃዎች በኩል ወሰንከሮ ብራታና ሙያትን መገንባት ይችላሉ።',
    homeProgressTracking: 'እድገት ክትትል',
    homeProgressDesc: 'ትምህርት ማጠናቀቂያ, የፈተና ውጤቶች, እና የመማር ስኬቶች ሙሉ ጉዞዎ ክትትል ይደረጋል።',
    homePlatformFeatures: 'ዋንጫ ባህሪዎች',
    homeVideoLessons: 'ቪዴዮ ላይ ተሠራ ትምህርቶች',
    homeInteractiveAssessments: 'ተስተ ግምገማዎች',
    homeLevelUnlock: 'ደረጃ ክፈት ስርዓት',
    homeLessonDiscovery: 'ትምህርት ግኝታ',
    homeAccessibleLearning: 'ተደራሽ ማመልከቻ',
    homeHowTitle: 'እንዴት ይሠራል',
    homeStep1: 'ሂሳብ ፍጠር',
    homeStep2: 'ደረጃ ግምገማ ውሰድ',
    homeStep3: 'ትምህርቶች መማር ይጀምር',
    homeStep4: 'እድገት ክትትል እና ማሻሻል',
    homeInclusiveComm: 'ሚያገናኙ ግንኙነት',
    homeInclusiveDesc: 'የኢትዮጵያ የምልክት ቋንቋ ግንኙነት ክፍተቶች ለመዝጋት ይረዳ።',
    homeWhyLearn: 'የኢትዮጵያ የምልክት ቋንቋ ለምን ይማሩ?',
    homeWhyLearnDesc: 'የምልክት ቋንቋ ማወቅ ግንኙነት ይጠነካራ ይህም ሚያገናኙነት ሲሠራ ፍትሐዊ ዕድሎች ሲደገሙ እና ማህበረሰቡ ተሳታፊ ይሆናል።',
    homeFaqTitle: 'በተደጋጋሚ የሚነሱ ጥያቄዎች',
    homeFaq1Q: 'ቀዳሚ ልምምድ ያስፈልገ?',
    homeFaq1A: 'አይ። ETHSL ለጀማሪዎች እና ሁሉም ደረጃ ተማሪዎች ይሠራል።',
    homeFaq2Q: 'ዋንጫ ነፃ ነው?',
    homeFaq2A: 'አዎ። ተማሪዎች ትምህርታዊ መሳሪያዎችን ያለ ወጭ ሊደርሱ ይችላሉ።',
    homeFaq3Q: 'በሞባይል መሳሪያ ሊማሩ ይችላሉ?',
    homeFaq3A: 'ስሌት። ETHSL በገንዘቦች, ታብሌቶች, እና ስማርትፎኖች ላይ ይሠራ።',
    homeContactTitle: 'ያናግሩን',
    homeContactDesc: 'ጥያቄዎች, ሃሳቦች, ወይም አስተያየት አለዎት?',
    homeContactDesc2: 'ከእናንተ ሰምተን ማግኘት ይፈልጋሉ።',
    homeLangToggle: 'English',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const { user } = useAuth()

  // For authenticated users, language comes from their profile.
  // For unauthenticated pages (Home, Login, Register), use localStorage.
  const storedLang = typeof window !== 'undefined'
    ? (localStorage.getItem('ethsl_lang') || 'en')
    : 'en'
  const lang = user?.language || storedLang

  const t = useCallback((key) => translations[lang]?.[key] ?? translations.en[key] ?? key, [lang])

  const toggleLanguage = useCallback(async () => {
    const newLang = lang === 'en' ? 'am' : 'en'
    // Always persist to localStorage so unauthenticated pages work
    localStorage.setItem('ethsl_lang', newLang)
    if (user) {
      // Also persist to backend for authenticated users
      try {
        await api.patch('/users/profile/', { language: newLang })
      } catch (e) {
        console.error('[LanguageContext] Failed to save language to backend:', e)
      }
    }
    window.location.reload()
  }, [lang, user])

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
