# Generated by Django 5.2.11 on 2026-05-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_warning_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='warning_message',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='placement_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='placement_required',
            field=models.BooleanField(default=False),
        ),
    ]
