# Generated by Django 5.2.11 on 2026-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_warning_message_user_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='placement_passed',
        ),
        migrations.AddField(
            model_name='user',
            name='warning_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
