# Generated by Django 5.2.11 on 2026-05-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_placement_passed_user_warning_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='placement_passed',
            field=models.BooleanField(default=False),
        ),
    ]
