# Generated by Django 5.2.11 on 2026-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_warning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', max_length=2),
        ),
    ]
